# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.api.notes_api import NotesApi  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_swagger.api.notes_api.NotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notes_list(self):
        """Test case for notes_list

        """
        pass

    def test_notes_partial_update(self):
        """Test case for notes_partial_update

        """
        pass

    def test_notes_read(self):
        """Test case for notes_read

        """
        pass

    def test_notes_update(self):
        """Test case for notes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
