# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.api.users_api import UsersApi  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_swagger.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_list(self):
        """Test case for users_list

        """
        pass

    def test_users_read(self):
        """Test case for users_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
