# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.models.stub_finding_create import StubFindingCreate  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestStubFindingCreate(unittest.TestCase):
    """StubFindingCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStubFindingCreate(self):
        """Test StubFindingCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = defectdojo_api_swagger.models.stub_finding_create.StubFindingCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
