# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.models.note_history import NoteHistory  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestNoteHistory(unittest.TestCase):
    """NoteHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteHistory(self):
        """Test NoteHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = defectdojo_api_swagger.models.note_history.NoteHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
