# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.api.jira_configurations_api import JiraConfigurationsApi  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestJiraConfigurationsApi(unittest.TestCase):
    """JiraConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_swagger.api.jira_configurations_api.JiraConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jira_configurations_create(self):
        """Test case for jira_configurations_create

        """
        pass

    def test_jira_configurations_delete(self):
        """Test case for jira_configurations_delete

        """
        pass

    def test_jira_configurations_list(self):
        """Test case for jira_configurations_list

        """
        pass

    def test_jira_configurations_partial_update(self):
        """Test case for jira_configurations_partial_update

        """
        pass

    def test_jira_configurations_read(self):
        """Test case for jira_configurations_read

        """
        pass

    def test_jira_configurations_update(self):
        """Test case for jira_configurations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
