# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.api.note_type_api import NoteTypeApi  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestNoteTypeApi(unittest.TestCase):
    """NoteTypeApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_swagger.api.note_type_api.NoteTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_note_type_create(self):
        """Test case for note_type_create

        """
        pass

    def test_note_type_delete(self):
        """Test case for note_type_delete

        """
        pass

    def test_note_type_list(self):
        """Test case for note_type_list

        """
        pass

    def test_note_type_partial_update(self):
        """Test case for note_type_partial_update

        """
        pass

    def test_note_type_read(self):
        """Test case for note_type_read

        """
        pass

    def test_note_type_update(self):
        """Test case for note_type_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
