# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_swagger
from defectdojo_api_swagger.api.api_token_auth_api import ApiTokenAuthApi  # noqa: E501
from defectdojo_api_swagger.rest import ApiException


class TestApiTokenAuthApi(unittest.TestCase):
    """ApiTokenAuthApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_swagger.api.api_token_auth_api.ApiTokenAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_token_auth_create(self):
        """Test case for api_token_auth_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
