# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FindingToNotes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'finding_id': 'int',
        'notes': 'list[Note]'
    }

    attribute_map = {
        'finding_id': 'finding_id',
        'notes': 'notes'
    }

    def __init__(self, finding_id=None, notes=None):  # noqa: E501
        """FindingToNotes - a model defined in Swagger"""  # noqa: E501

        self._finding_id = None
        self._notes = None
        self.discriminator = None

        self.finding_id = finding_id
        self.notes = notes

    @property
    def finding_id(self):
        """Gets the finding_id of this FindingToNotes.  # noqa: E501


        :return: The finding_id of this FindingToNotes.  # noqa: E501
        :rtype: int
        """
        return self._finding_id

    @finding_id.setter
    def finding_id(self, finding_id):
        """Sets the finding_id of this FindingToNotes.


        :param finding_id: The finding_id of this FindingToNotes.  # noqa: E501
        :type: int
        """
        if finding_id is None:
            raise ValueError("Invalid value for `finding_id`, must not be `None`")  # noqa: E501

        self._finding_id = finding_id

    @property
    def notes(self):
        """Gets the notes of this FindingToNotes.  # noqa: E501


        :return: The notes of this FindingToNotes.  # noqa: E501
        :rtype: list[Note]
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this FindingToNotes.


        :param notes: The notes of this FindingToNotes.  # noqa: E501
        :type: list[Note]
        """
        if notes is None:
            raise ValueError("Invalid value for `notes`, must not be `None`")  # noqa: E501

        self._notes = notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FindingToNotes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingToNotes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
