# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_client
from defectdojo_api_client.api.jira_product_configurations_api import JiraProductConfigurationsApi  # noqa: E501
from defectdojo_api_client.rest import ApiException


class TestJiraProductConfigurationsApi(unittest.TestCase):
    """JiraProductConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_client.api.jira_product_configurations_api.JiraProductConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jira_product_configurations_create(self):
        """Test case for jira_product_configurations_create

        """
        pass

    def test_jira_product_configurations_delete(self):
        """Test case for jira_product_configurations_delete

        """
        pass

    def test_jira_product_configurations_list(self):
        """Test case for jira_product_configurations_list

        """
        pass

    def test_jira_product_configurations_partial_update(self):
        """Test case for jira_product_configurations_partial_update

        """
        pass

    def test_jira_product_configurations_read(self):
        """Test case for jira_product_configurations_read

        """
        pass

    def test_jira_product_configurations_update(self):
        """Test case for jira_product_configurations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
