# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import defectdojo_api_client
from defectdojo_api_client.models.development_environment import DevelopmentEnvironment  # noqa: E501
from defectdojo_api_client.rest import ApiException

class TestDevelopmentEnvironment(unittest.TestCase):
    """DevelopmentEnvironment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DevelopmentEnvironment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = defectdojo_api_client.models.development_environment.DevelopmentEnvironment()  # noqa: E501
        if include_optional :
            return DevelopmentEnvironment(
                id = 56, 
                name = '0'
            )
        else :
            return DevelopmentEnvironment(
                name = '0',
        )

    def testDevelopmentEnvironment(self):
        """Test DevelopmentEnvironment"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
