# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import defectdojo_api_client
from defectdojo_api_client.api.reimport_scan_api import ReimportScanApi  # noqa: E501
from defectdojo_api_client.rest import ApiException


class TestReimportScanApi(unittest.TestCase):
    """ReimportScanApi unit test stubs"""

    def setUp(self):
        self.api = defectdojo_api_client.api.reimport_scan_api.ReimportScanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reimport_scan_create(self):
        """Test case for reimport_scan_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
