# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import defectdojo_api_client
from defectdojo_api_client.models.add_new_note_option import AddNewNoteOption  # noqa: E501
from defectdojo_api_client.rest import ApiException

class TestAddNewNoteOption(unittest.TestCase):
    """AddNewNoteOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AddNewNoteOption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = defectdojo_api_client.models.add_new_note_option.AddNewNoteOption()  # noqa: E501
        if include_optional :
            return AddNewNoteOption(
                entry = '0', 
                private = True, 
                note_type = 56
            )
        else :
            return AddNewNoteOption(
                entry = '0',
        )

    def testAddNewNoteOption(self):
        """Test AddNewNoteOption"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
