# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import defectdojo_api_client
from defectdojo_api_client.models.jira_issue import JIRAIssue  # noqa: E501
from defectdojo_api_client.rest import ApiException

class TestJIRAIssue(unittest.TestCase):
    """JIRAIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JIRAIssue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = defectdojo_api_client.models.jira_issue.JIRAIssue()  # noqa: E501
        if include_optional :
            return JIRAIssue(
                id = 56, 
                jira_id = '0', 
                jira_key = '0', 
                finding = 56, 
                engagement = 56
            )
        else :
            return JIRAIssue(
                jira_id = '0',
                jira_key = '0',
        )

    def testJIRAIssue(self):
        """Test JIRAIssue"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
