# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import defectdojo_api_client
from defectdojo_api_client.models.endpoint import Endpoint  # noqa: E501
from defectdojo_api_client.rest import ApiException

class TestEndpoint(unittest.TestCase):
    """Endpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Endpoint
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = defectdojo_api_client.models.endpoint.Endpoint()  # noqa: E501
        if include_optional :
            return Endpoint(
                id = 56, 
                tags = [
                    '0'
                    ], 
                protocol = '0', 
                host = '0', 
                fqdn = '0', 
                port = -2147483648, 
                path = '0', 
                query = '0', 
                fragment = '0', 
                remediated = True, 
                product = 56, 
                endpoint_params = [
                    56
                    ]
            )
        else :
            return Endpoint(
        )

    def testEndpoint(self):
        """Test Endpoint"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
